#!/bin/bash

error() {
    echo "$1" >&2   ## Send message to stderr
                    ## Exclude >&2 if you don't want it that way.
    exit "${2:-1}"  ## Return a code specified by $2 or 1 by default.
}

git_arg_check(){
  if test $1 -ne $2; then
    echo "$(printf $ANSI_RED)error$(printf $ANSI_RESET):" "$3" 'takes' "$2" 'arguments, supplied' "$1"
    echo "$(printf $ANSI_YELLOW)useage$(printf $ANSI_RESET):" "$3" "${@:4}"
    exit 1
  fi
}

#  input:
#    $1=project name
git_genesis(){
  git_arg_check $# 1 $FUNCNAME 'project_name' &&
  git init --bare $1_repo &&
  git clone $1_repo $1 &&
  cd $1 &&
  git commit --allow-empty -m "init: Null commit" -m "(master/): Commit early, commit often." &&
  git push &&
  git branch development &&
  git push -u origin development &&
  cd ..
}

#  input:
#    $1=project name
#    $2=origin remote
git_introduce(){
  git_arg_check $# 2 $FUNCNAME 'project_name' 'origin_remote'
  cd "$1"
  git remote add origin "$2"
  git remote add all "$2"
  git push -u origin --all
  git push -u origin --tags
  cd ..
}

#  input:
#    $1=project name
#    $2=gitlab username
git_introgitlab(){
  git_arg_check $# 2 $FUNCNAME 'project_name' 'gitlab_username'
  gitlab_origin="git@gitlab.com:$2/$1.git"
  cd "$1"_repo
  git push --set-upstream "$gitlab_origin" master
  git remote add origin-gitlab "$gitlab_origin"
  git push -u origin-gitlab --all
  git push -u origin-gitlab --tags
  cd ../"$1"
  git remote add origin-gitlab "$gitlab_origin"
  git remote add all "$gitlab_origin"
  git remote set-url --add --push all "$gitlab_origin"
  cd ..
}

#  input:
#    $1=git repo name
#    $2=github username
git_introgithub(){
  git_arg_check $# 2 $FUNCNAME 'project_name' 'github_username'
  github_origin="git@github.com:$2/$1.git"
  cd $1_repo
  github_string='{"name":"'"$1"'","private":"true"}'
  curl -u "$2" https://api.github.com/user/repos -d "$github_string"
  git remote add origin-github "$github_origin"
  git push -u origin-github --all
  git push -u origin-github --tags
  cd ../$1
  git remote add origin-github "$github_origin"
  git remote set-url --add --push all "$github_origin"
  cd ..
}

#  input:
#    $1=project name
#    $2=origin remote
git_death_of_a_salesman(){
  git_arg_check $# 2 $FUNCNAME 'project_name' 'origin_remote'
  cd $1
  git remote set-url origin $2
  cd ..
  rm -rf $1_repo
}

#  input:
#    $1=project name
#    $2=origin remote
git_omnistart(){
  git_arg_check $# 2 $FUNCNAME 'project_name' 'origin_remote' &&
  git_genesis $1 &&
  git_introduce $1_repo $2 &&
  git_death_of_a_salesman $1 $2
}

#  input:
#    $1=project name
#    $2=gitlab username
#    $3=github username
git_initwww(){
  git_arg_check $# 3 $FUNCNAME 'project_name' 'gitlab_username' 'github_username' &&
  git_genesis $1 &&
  git_introgitlab $1 $2 &&
  git_introgithub $1 $3 &&
  git_death_of_a_salesman $1 "git@gitlab.com:$2/$1.git"
}
