:filetype on
:syntax on
:set background=dark
:set wildmenu
:set ruler
colorscheme gruvbox
if &diff
  colorscheme luna
endif

map Y $y

" gitcommit options
au FileType gitcommit call SetGitOptions()
au FileType python call SetPythonOptions()

function SetGitOptions()
setlocal tw=72
setlocal spell spelllang=en_gb
endfunction

function SetPythonOptions()
setlocal tw=80
setlocal ts=4
setlocal sw=4
endfunction

let @o='do]czz'
let @p='dp]czz'
